apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  labels:
    app: webapp
data:
  MONGODB_HOST: mongodb
  MONGODB_USERNAME: potatoes
  MONGODB_PASSWORD: potatoes
  MONGODB_DB: potatoes
  MONGODB_PORT: "27017"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  labels:
    app: mongodb
data:
  MONGO_INITDB_ROOT_USERNAME: potatoes
  MONGO_INITDB_ROOT_PASSWORD: potatoes